### ISSUE TITLE
使用consul作为注册中心，但是服务能发布，消费者却订阅失败，提示如下

### ISSUE THREAD

**Issue by whh5233** [alipay/sofa-rpc-boot-projects#151]
Exception in thread "main" com.alipay.sofa.rpc.core.exception.SofaRouteException: RPC-02306: 没有获得服务[com.alipay.sofa.rpc.samples.direct.DirectService:1.0]的调用地址，请检查服务是否已经推送 
	at com.alipay.sofa.rpc.client.AbstractCluster.noAvailableProviderException(AbstractCluster.java:423)
	at com.alipay.sofa.rpc.client.AbstractCluster.select(AbstractCluster.java:358)
	at com.alipay.sofa.rpc.client.FailoverCluster.doInvoke(FailoverCluster.java:64)
	at com.alipay.sofa.rpc.client.AbstractCluster.invoke(AbstractCluster.java:285)
	at com.alipay.sofa.rpc.client.ClientProxyInvoker.invoke(ClientProxyInvoker.java:83)
	at com.alipay.sofa.rpc.samples.direct.DirectService_proxy_0.sayDirect(DirectService_proxy_0.java)
	at com.alipay.sofa.rpc.samples.direct.DirectClientApplication.main(DirectClientApplication.java:42)

**Comment by JervyShi** [comment]
@whh5233 感谢反馈，Consul 目前作为预览版还存在一些已知问题待解决，这块的实现后续会重构一下，可以先尝试使用下其他注册中心实现，当前也可以考虑帮助我们一次完善下对 Consul 的支持，感谢！
