### ISSUE TITLE
mvn打包报错问题

### ISSUE THREAD

**Issue by wangxiaotao00** [alipay/sofa-rpc-boot-projects#35]
使用mvn clean install打包报错，提示找不到resource下面的xml

**Comment by NeGnail** [comment]
错误堆栈贴一下吧

**Comment by wangxiaotao00** [comment]
2018-05-05 13:34:18.805  INFO 7261 --- [           main] o.s.b.f.xml.XmlBeanDefinitionReader      : Loading XML bean definitions from ServletContext resource [/rest-server.xml]
2018-05-05 13:34:18.806  WARN 7261 --- [           main] o.s.w.c.s.GenericWebApplicationContext   : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanDefinitionStoreException: IOException parsing XML document from ServletContext resource [/rest-server.xml]; nested exception is java.io.FileNotFoundException: Could not open ServletContext resource [/rest-server.xml]
2018-05-05 13:34:18.809 ERROR 7261 --- [           main] o.s.b.f.s.DefaultListableBeanFactory     : Destroy method on bean with name 'org.springframework.boot.autoconfigure.internalCachingMetadataReaderFactory' threw an exception

java.lang.IllegalStateException: ApplicationEventMulticaster not initialized - call 'refresh' before multicasting events via the context: org.springframework.web.context.support.GenericWebApplicationContext@40052776: startup date [Sat May 05 13:34:18 CST 2018]; root of context hierarchy
	at org.springframework.context.support.AbstractApplicationContext.getApplicationEventMulticaster(AbstractApplicationContext.java:404) [spring-context-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.context.support.ApplicationListenerDetector.postProcessBeforeDestruction(ApplicationListenerDetector.java:97) ~[spring-context-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:253) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:578) [spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:554) [spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:954) [spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:523) [spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:961) [spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1033) [spring-context-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:555) [spring-context-4.3.4.RELEASE.jar:4.3.4.RELEASE]

**Comment by leizhiyuan** [comment]
rest-server.xml 这个是你自己的文件吧.看下你的 xml 放在哪里的. 配置的 xml 位置是否正确.

**Comment by wangxiaotao00** [comment]
放在resources/下面的

**Comment by leizhiyuan** [comment]
你的启动类配置呢?

**Comment by wangxiaotao00** [comment]
@ImportResource({"rest-server.xml","rest-client.xml"}) // 引入加载的 spring xml
public class SpringBootSseApplication {

**Comment by leizhiyuan** [comment]
@wangxiaotao00 参考 demo 用例看一下,要带上 classpath 相关.

```
@ImportResource({ "classpath:rpc.xml" })

```

**Comment by wangxiaotao00** [comment]
好的，谢谢
