### ISSUE TITLE
SofaBoot RPC demo 不能正常工作

### ISSUE THREAD

**Issue by Vartangwb** [alipay/sofa-rpc-boot-projects#45]
### Your question

按照https://github.com/alipay/sofa-rpc-boot-projects/wiki/GettingStarted，搭建项目并设置相关配置，
当直接run整个application时，会提示下边的SofaRouteException
Exception in thread "main" com.alipay.sofa.rpc.core.exception.SofaRouteException: RPC-02306: 没有获得服务[com.example.demo.Service.HelloSyncService:1.0]的调用地址，请检查服务是否已经推送 
	at com.alipay.sofa.rpc.client.AbstractCluster.noAvailableProviderException(AbstractCluster.java:419)
	at com.alipay.sofa.rpc.client.AbstractCluster.select(AbstractCluster.java:391)
	at com.alipay.sofa.rpc.client.FailoverCluster.doInvoke(FailoverCluster.java:64)
	at com.alipay.sofa.rpc.client.AbstractCluster.invoke(AbstractCluster.java:286)
	at com.alipay.sofa.rpc.client.ClientProxyInvoker.invoke(ClientProxyInvoker.java:83)
	at com.alipay.sofa.rpc.proxy.jdk.JDKInvocationHandler.invoke(JDKInvocationHandler.java:74)
	at com.sun.proxy.$Proxy52.saySync(Unknown Source)
	at com.example.demo.DemoApplication.main(DemoApplication.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
但是当在main函数的 System.out.println(helloSyncServiceReference.saySync("sync"));所对应的行打断点进行调试时 最终能够正确返回saySync函数所对应的结果？所以想问下你们在实现demo的时候有没有遇到过类似的问题

`
public static void main(String[] args) throws Exception{

		SpringApplication springApplication = new SpringApplication(DemoApplication.class);

		ApplicationContext applicationContext = springApplication.run(args);

		HelloSyncService helloSyncServiceReference = (HelloSyncService) applicationContext
				.getBean("helloSyncServiceReference")

		System.out.println(helloSyncServiceReference.saySync("sync"));
}
`

### Environment

- Starter version: sofa boot parent:2.3.1
- JVM version (e.g. `java -version`): 1.8.0_77
- OS version (e.g. `uname -a`):  WIN7
- Maven version: 3.3.9
- IDE version: IDEA 16.3

**Comment by leizhiyuan** [comment]
没有配置 lazy 之前,可以现在

```
HelloSyncService helloSyncServiceReference = (HelloSyncService) applicationContext
			.getBean("helloSyncServiceReference")
Thread.sleep(6000);//加一行
	System.out.println(helloSyncServiceReference.saySync("sync"));
```

加一行 sleep

**Comment by NeGnail** [comment]
这是由于启动调用太快，地址还没有推送下来。你可以在调用之前sleep(1000)来解决。

**Comment by leizhiyuan** [comment]
没问题先关闭了,有问题麻烦再打开这个 issue
